[project]
name = "heartbeat-reborn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "moritz", email = "sergeial1972@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "uvicorn>=0.35.0"
]

[project.scripts]
heartbeat-reborn = "heartbeat_reborn:main"
